services:
  - type: web
    name: tron-wallet-frontend
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_API_BASE_URL
        fromService:
          name: tron-wallet-backend
          type: web
          property: url
      - key: VITE_PROJECT_ID
        value: df98a5acab79dd9d0a3789574ccf6dab

  - type: web
    name: tron-wallet-backend
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: HOST
        value: 0.0.0.0
      - key: BASE_URL
        value: https://tron-wallet-backend.onrender.com